/** @file cmdline.h
 *  @brief The header file for the command line option parser
 *  generated by GNU Gengetopt version 2.22.2
 *  http://www.gnu.org/software/gengetopt.
 *  DO NOT modify this file, since it can be overwritten
 *  @author GNU Gengetopt by Lorenzo Bettini */

#ifndef CMDLINE_H
#define CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h> /* for FILE */

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
/** @brief the program name (used for printing errors) */
#define CMDLINE_PARSER_PACKAGE "qemu-start"
#endif

#ifndef CMDLINE_PARSER_PACKAGE_NAME
/** @brief the complete program name (used for help and version) */
#define CMDLINE_PARSER_PACKAGE_NAME "qemu-start"
#endif

#ifndef CMDLINE_PARSER_VERSION
/** @brief the program version */
#define CMDLINE_PARSER_VERSION "2.0"
#endif

/** @brief Where the command line options are stored */
struct gengetopt_args_info
{
  const char *help_help; /**< @brief Print help and exit help description.  */
  const char *version_help; /**< @brief Print version and exit help description.  */
  int tapnr_arg;	/**< @brief Universal TUN/TAP device number (e.g. 0 for tap0) (default='0').  */
  char * tapnr_orig;	/**< @brief Universal TUN/TAP device number (e.g. 0 for tap0) original value given at command line.  */
  const char *tapnr_help; /**< @brief Universal TUN/TAP device number (e.g. 0 for tap0) help description.  */
  int vlan_arg;	/**< @brief Virtual LAN (VLAN) number (e.g. 0) (default='0').  */
  char * vlan_orig;	/**< @brief Virtual LAN (VLAN) number (e.g. 0) original value given at command line.  */
  const char *vlan_help; /**< @brief Virtual LAN (VLAN) number (e.g. 0) help description.  */
  char * macaddr_arg;	/**< @brief MAC address of guest emulated NIC.  */
  char * macaddr_orig;	/**< @brief MAC address of guest emulated NIC original value given at command line.  */
  const char *macaddr_help; /**< @brief MAC address of guest emulated NIC help description.  */
  char * nic_model_arg;	/**< @brief Model of guest emulated NIC.  */
  char * nic_model_orig;	/**< @brief Model of guest emulated NIC original value given at command line.  */
  const char *nic_model_help; /**< @brief Model of guest emulated NIC help description.  */
  char * system_arg;	/**< @brief Type of system to emulate (e.g. PPC), calls qemu-system-<system>.  If left blank /usr/bin/qemu is called..  */
  char * system_orig;	/**< @brief Type of system to emulate (e.g. PPC), calls qemu-system-<system>.  If left blank /usr/bin/qemu is called. original value given at command line.  */
  const char *system_help; /**< @brief Type of system to emulate (e.g. PPC), calls qemu-system-<system>.  If left blank /usr/bin/qemu is called. help description.  */
  int window_left_arg;	/**< @brief Left position of SDL screen (e.g. for use with -no-frame).  */
  char * window_left_orig;	/**< @brief Left position of SDL screen (e.g. for use with -no-frame) original value given at command line.  */
  const char *window_left_help; /**< @brief Left position of SDL screen (e.g. for use with -no-frame) help description.  */
  int window_top_arg;	/**< @brief Top position of SDL screen (e.g. for use with -no-frame).  */
  char * window_top_orig;	/**< @brief Top position of SDL screen (e.g. for use with -no-frame) original value given at command line.  */
  const char *window_top_help; /**< @brief Top position of SDL screen (e.g. for use with -no-frame) help description.  */
  
  unsigned int help_given ;	/**< @brief Whether help was given.  */
  unsigned int version_given ;	/**< @brief Whether version was given.  */
  unsigned int tapnr_given ;	/**< @brief Whether tapnr was given.  */
  unsigned int vlan_given ;	/**< @brief Whether vlan was given.  */
  unsigned int macaddr_given ;	/**< @brief Whether macaddr was given.  */
  unsigned int nic_model_given ;	/**< @brief Whether nic-model was given.  */
  unsigned int system_given ;	/**< @brief Whether system was given.  */
  unsigned int window_left_given ;	/**< @brief Whether window-left was given.  */
  unsigned int window_top_given ;	/**< @brief Whether window-top was given.  */

  char **inputs ; /**< @brief unamed options (options without names) */
  unsigned inputs_num ; /**< @brief unamed options number */
} ;

/** @brief The additional parameters to pass to parser functions */
struct cmdline_parser_params
{
  int override; /**< @brief whether to override possibly already present options (default 0) */
  int initialize; /**< @brief whether to initialize the option structure gengetopt_args_info (default 1) */
  int check_required; /**< @brief whether to check that all required options were provided (default 1) */
  int check_ambiguity; /**< @brief whether to check for options already specified in the option structure gengetopt_args_info (default 0) */
  int print_errors; /**< @brief whether getopt_long should print an error message for a bad option (default 1) */
} ;

/** @brief the purpose string of the program */
extern const char *gengetopt_args_info_purpose;
/** @brief the usage string of the program */
extern const char *gengetopt_args_info_usage;
/** @brief all the lines making the help output */
extern const char *gengetopt_args_info_help[];

/**
 * The command line parser
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);

/**
 * The command line parser (version with additional parameters - deprecated)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param override whether to override possibly already present options
 * @param initialize whether to initialize the option structure my_args_info
 * @param check_required whether to check that all required options were provided
 * @return 0 if everything went fine, NON 0 if an error took place
 * @deprecated use cmdline_parser_ext() instead
 */
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);

/**
 * The command line parser (version with additional parameters)
 * @param argc the number of command line options
 * @param argv the command line options
 * @param args_info the structure where option information will be stored
 * @param params additional parameters for the parser
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_ext (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  struct cmdline_parser_params *params);

/**
 * Save the contents of the option struct into an already open FILE stream.
 * @param outfile the stream where to dump options
 * @param args_info the option struct to dump
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_dump(FILE *outfile,
  struct gengetopt_args_info *args_info);

/**
 * Save the contents of the option struct into a (text) file.
 * This file can be read by the config file parser (if generated by gengetopt)
 * @param filename the file where to save
 * @param args_info the option struct to save
 * @return 0 if everything went fine, NON 0 if an error took place
 */
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

/**
 * Print the help
 */
void cmdline_parser_print_help(void);
/**
 * Print the version
 */
void cmdline_parser_print_version(void);

/**
 * Initializes all the fields a cmdline_parser_params structure 
 * to their default values
 * @param params the structure to initialize
 */
void cmdline_parser_params_init(struct cmdline_parser_params *params);

/**
 * Allocates dynamically a cmdline_parser_params structure and initializes
 * all its fields to their default values
 * @return the created and initialized cmdline_parser_params structure
 */
struct cmdline_parser_params *cmdline_parser_params_create(void);

/**
 * Initializes the passed gengetopt_args_info structure's fields
 * (also set default values for options that have a default)
 * @param args_info the structure to initialize
 */
void cmdline_parser_init (struct gengetopt_args_info *args_info);
/**
 * Deallocates the string fields of the gengetopt_args_info structure
 * (but does not deallocate the structure itself)
 * @param args_info the structure to deallocate
 */
void cmdline_parser_free (struct gengetopt_args_info *args_info);

/**
 * Checks that all the required options were specified
 * @param args_info the structure to check
 * @param prog_name the name of the program that will be used to print
 *   possible errors
 * @return
 */
int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* CMDLINE_H */
